server:
  port: 8082
spring:
  application:
    name: notification
  datasource:
    username: 'naman'
    url: jdbc:postgresql://localhost:5432/notification
    password: 'password'
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'
  zipkin:
    base-url: http://localhost:9411/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
