server:
  port: 8082
spring:
  application:
    name: notification
  datasource:
    username: 'naman'
    url: jdbc:postgresql://postgres:5432/notification
    password: 'password'
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'
  zipkin:
    base-url: http://zipkin:9411/
  rabbitmq:
    addresses: rabbitmq:5672

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

rabbitmq:
  exchanges:
    internal: internal.exchange
  queue:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key